# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/kaarel/Downloads/Ticket-Booking-System/ui_design_files/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 310, 210))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gotocustomers = QtWidgets.QPushButton(self.layoutWidget)
        self.gotocustomers.setObjectName("gotocustomers")
        self.verticalLayout.addWidget(self.gotocustomers)
        self.gotobookings = QtWidgets.QPushButton(self.layoutWidget)
        self.gotobookings.setObjectName("gotobookings")
        self.verticalLayout.addWidget(self.gotobookings)
        self.gotoseats = QtWidgets.QPushButton(self.layoutWidget)
        self.gotoseats.setObjectName("gotoseats")
        self.verticalLayout.addWidget(self.gotoseats)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Ticket Booking System"))
        self.gotocustomers.setText(_translate("Dialog", "Search through customers"))
        self.gotobookings.setText(_translate("Dialog", "Search through bookings"))
        self.gotoseats.setText(_translate("Dialog", "Search through seats"))
