# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main-window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 10, 310, 210))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.showid = QtWidgets.QLineEdit(self.widget)
        self.showid.setText("")
        self.showid.setObjectName("showid")
        self.horizontalLayout_2.addWidget(self.showid)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gotocustomers = QtWidgets.QPushButton(self.widget)
        self.gotocustomers.setObjectName("gotocustomers")
        self.verticalLayout.addWidget(self.gotocustomers)
        self.gotobookings = QtWidgets.QPushButton(self.widget)
        self.gotobookings.setObjectName("gotobookings")
        self.verticalLayout.addWidget(self.gotobookings)
        self.gotoseats = QtWidgets.QPushButton(self.widget)
        self.gotoseats.setObjectName("gotoseats")
        self.verticalLayout.addWidget(self.gotoseats)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "ShowID"))
        self.gotocustomers.setText(_translate("Dialog", "Search through customers"))
        self.gotobookings.setText(_translate("Dialog", "Search through bookings"))
        self.gotoseats.setText(_translate("Dialog", "Search through seats"))
